---
- name: My First Ansible Playbook
  hosts: web-servers
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    # - name: Update apt package cache
    #   apt:
    #     update_cache: yes
    #   when: ansible_os_family == "Debian"

    - name: Install Nginx package
      package:
        name: nginx
        state: present

    - name: Start and Enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        content: "<h1>Hello from {{ ansible_hostname }}!</h1>"
        dest: /var/www/html/index.html
